# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: totomz
description: "Tommaso Doninelli personal notebook"
keywords: "AWS, Cloud Solution Architect, devops, cloud, aws"
url: https://totomz.github.io
baseurl: ""

google_analytics: UA-80722776-3
repo: http://github.com/totomz/totomz.github.io
disqus_shortname: "totomzgithubio"
disqus_site_shortname: "totomzgithubio"

# Author settings
author:
  name: Tommaso Doninelli
  job: CTO and Cloud Solution Architect
  bio: "Always looking for the best project"
  thumb: https://www.gravatar.com/avatar/9f61771330a110b3d67767af7c8b08cd?s=100
  email: tommaso.doninelli@gmail.com
  url: https://totomz.github.io/
  github: https://github.com/totomz
  twitter: https://twitter.com/glicerina_
  facebook: https://www.facebook.com/zuccherocaramellato84
  linkedin: https://www.linkedin.com/in/tdoninelli/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
